### ISSUE TITLE
Messages sent by publisher before one second are not received by the subscriber

### ISSUE THREAD

**Issue by kkwoker** [colstrom/ezmq#8]
It looks like the messages that the publisher sends before 1 second are sent, but are lost on transmission to the subscriber. 

``` ruby
# publisher.rb
require 'ezmq'

$logger = EZMQ::Publisher.new

def log message
  puts $logger.send message, topic: 'logging'
end

# These messages are lost, but are sent by the publisher
log "Hello one"
log "Hello two"
log "Hello three"

sleep 1
# Only these messages are received by the subscriber
log "Hello four"
log "Hello five"
log "Hello six"
```

``` ruby
# subscriber.rb
require 'ezmq'

listener = EZMQ::Subscriber.new topic: 'logging'

listener.listen do |message, topic|
  puts "#{topic}: #{message}"
end
```

**Comment by kkwoker** [comment]
```
$ ruby publisher.rb                                                                            Mon 29 Jun 2015 10:29:22 PDT
    17
    17
    19
    18
    18
    17
```

```
$ ruby subscriber.rb                                                                           Mon 29 Jun 2015 10:29:15 PDT
    logging: Hello four
    logging: Hello five
    logging: Hello six
```

**Comment by colstrom** [comment]
I'm pretty sure we discussed this in meatspace when this issue was opened, but in case I didn't... 

This is correct behaviour. A `Publisher` does not depend on a `Subscriber` being present. It simply broadcasts to whoever happens to be listening. Alternatives would be blocking or failing. Even if we confirmed a non-zero connection count on the socket before sending, what happens when none of them are listening to the topic being sent? All of these things can be addressed one way or another, at the cost of complexity. However, if you need to ensure delivery, a PUB->SUB may not be the most appropriate pattern.
